version: '3.1'

services:
  zookeeper:
    image: zookeeper
    # restart: always
    # hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
  kafka:
    image: confluentinc/cp-kafka
    # restart: always
    # hostname: kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092 
# docker compose -f docker-compose.yml up -d